import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";
import {
  ensureProjectRelease,
  uploadAssetToRelease,
} from "@/lib/storage/github";
import { writeFile, readFile, unlink, mkdir } from "fs/promises";
import { existsSync } from "fs";
import path from "path";
import os from "os";

export const runtime = "nodejs";
export const maxDuration = 60;

/**
 * Temporary directory where chunks are staged before being assembled and
 * uploaded to GitHub. This uses the OS temp directory which is available
 * on all Vercel plans (even Hobby) — it persists for the lifetime of the
 * serverless function instance.
 */
function chunkDir(projectId: string, uploadId: string): string {
  return path.join(os.tmpdir(), "ifc-chunks", projectId, uploadId);
}

/**
 * POST /api/ifc/stream-upload/:projectId
 *
 * Chunked upload flow that bypasses Vercel's ~4.5 MB body limit:
 *
 *   Headers:
 *     X-Upload-Id:    Unique ID for this upload session (generated by client)
 *     X-Chunk-Index:  Zero-based chunk index
 *     X-Total-Chunks: Total number of chunks
 *     X-Filename:     Original filename (sent on last chunk)
 *     Content-Type:   application/octet-stream
 *
 *   Body: raw binary chunk (max ~3.5 MB each)
 *
 *   Flow:
 *     1. Each chunk is saved to /tmp on the serverless function.
 *     2. On the LAST chunk, all chunks are assembled into a single buffer.
 *     3. The complete file is uploaded to GitHub Releases.
 *     4. The Supabase project record is updated.
 *     5. Temp files are cleaned up.
 *
 *   For files < 3.5 MB, the client sends a single chunk (index=0, total=1).
 */
export async function POST(
  req: Request,
  { params }: { params: Promise<{ projectId: string }> }
) {
  try {
    const { projectId } = await params;
    if (!projectId) {
      return NextResponse.json({ error: "Missing projectId" }, { status: 400 });
    }

    // --- Auth check ---
    const supabase = await createClient();
    const {
      data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
      return NextResponse.json({ error: "Não autenticado" }, { status: 401 });
    }

    const { data: project, error: projErr } = await supabase
      .from("projects")
      .select("owner_id")
      .eq("id", projectId)
      .maybeSingle();
    if (projErr || !project || project.owner_id !== user.id) {
      return NextResponse.json(
        { error: "Projeto não encontrado ou sem permissão" },
        { status: 403 }
      );
    }

    // --- Parse chunk metadata from headers ---
    const uploadId = req.headers.get("X-Upload-Id") || req.headers.get("x-upload-id");
    const chunkIndexStr =
      req.headers.get("X-Chunk-Index") || req.headers.get("x-chunk-index");
    const totalChunksStr =
      req.headers.get("X-Total-Chunks") || req.headers.get("x-total-chunks");
    const filename =
      req.headers.get("X-Filename") || req.headers.get("x-filename") || "model.ifc";

    if (!uploadId || chunkIndexStr == null || totalChunksStr == null) {
      return NextResponse.json(
        { error: "Headers obrigatórios: X-Upload-Id, X-Chunk-Index, X-Total-Chunks" },
        { status: 400 }
      );
    }

    const chunkIndex = parseInt(chunkIndexStr, 10);
    const totalChunks = parseInt(totalChunksStr, 10);

    if (
      isNaN(chunkIndex) ||
      isNaN(totalChunks) ||
      chunkIndex < 0 ||
      totalChunks < 1 ||
      chunkIndex >= totalChunks
    ) {
      return NextResponse.json(
        { error: "Valores inválidos para chunk index/total" },
        { status: 400 }
      );
    }

    // Sanitize uploadId to prevent path traversal
    const safeUploadId = uploadId.replace(/[^a-zA-Z0-9_-]/g, "");
    if (!safeUploadId || safeUploadId.length > 64) {
      return NextResponse.json({ error: "Upload ID inválido" }, { status: 400 });
    }

    // --- Save this chunk to /tmp ---
    const dir = chunkDir(projectId, safeUploadId);
    if (!existsSync(dir)) {
      await mkdir(dir, { recursive: true });
    }

    const body = await req.arrayBuffer();
    if (body.byteLength === 0) {
      return NextResponse.json({ error: "Chunk vazio" }, { status: 400 });
    }

    const chunkPath = path.join(dir, `chunk-${String(chunkIndex).padStart(5, "0")}`);
    await writeFile(chunkPath, Buffer.from(body));

    // --- If this is NOT the last chunk, just acknowledge ---
    if (chunkIndex < totalChunks - 1) {
      return NextResponse.json({
        ok: true,
        chunk: chunkIndex,
        totalChunks,
        status: "chunk_received",
      });
    }

    // --- LAST CHUNK: assemble and upload to GitHub ---
    const buffers: Buffer[] = [];
    for (let i = 0; i < totalChunks; i++) {
      const p = path.join(dir, `chunk-${String(i).padStart(5, "0")}`);
      if (!existsSync(p)) {
        return NextResponse.json(
          { error: `Chunk ${i} não encontrado — tente novamente` },
          { status: 400 }
        );
      }
      buffers.push(await readFile(p));
    }
    const fullBuffer = Buffer.concat(buffers);

    // Upload to GitHub
    const assetName = "model.ifc";
    const release = await ensureProjectRelease(projectId);
    const asset = await uploadAssetToRelease({
      release,
      filename: assetName,
      contentType: "application/octet-stream",
      body: fullBuffer,
      contentLength: fullBuffer.byteLength,
    });

    // Update Supabase
    const { error: updErr } = await supabase
      .from("projects")
      .update({
        ifc_storage: "github",
        ifc_release_id: release.id,
        ifc_asset_id: asset.id,
        ifc_asset_name: assetName,
        ifc_filename: filename,
        ifc_size_bytes: asset.size,
        ifc_path: null,
      })
      .eq("id", projectId);

    if (updErr) {
      return NextResponse.json(
        { error: `Upload OK mas falha no banco: ${updErr.message}` },
        { status: 500 }
      );
    }

    // Cleanup temp files (non-blocking)
    cleanup(dir, totalChunks).catch((e) =>
      console.warn("[stream-upload] cleanup error:", e)
    );

    return NextResponse.json({
      ok: true,
      filename,
      size: asset.size,
      storage: "github",
      status: "complete",
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Erro desconhecido";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

async function cleanup(dir: string, totalChunks: number) {
  for (let i = 0; i < totalChunks; i++) {
    const p = path.join(dir, `chunk-${String(i).padStart(5, "0")}`);
    await unlink(p).catch(() => {});
  }
  // Try removing the directory itself
  const { rmdir } = await import("fs/promises");
  await rmdir(dir).catch(() => {});
}
